2017-11-16 14:10:13,912 - root - host_connect.py[line:27] - INFO >>> host开始更新： stage1
2017-11-16 14:10:13,949 - root - host_connect.py[line:31] - INFO >>> host更新成功： stage1
2017-11-16 14:10:13,950 - root - execution_case.py[line:14] - INFO >>> 开始执行用例
2017-11-16 14:10:13,950 - root - ary.py[line:22] - INFO >>> 开始打开chrome浏览器
2017-11-16 14:10:22,380 - root - ary.py[line:30] - INFO >>> 打开浏览器成功
2017-11-16 14:12:14,222 - root - host_connect.py[line:27] - INFO >>> host开始更新： stage1
2017-11-16 14:12:14,225 - root - host_connect.py[line:31] - INFO >>> host更新成功： stage1
2017-11-16 14:12:14,225 - root - execution_case.py[line:14] - INFO >>> 开始执行用例
2017-11-16 14:12:36,019 - root - host_connect.py[line:27] - INFO >>> host开始更新： stage1
2017-11-16 14:12:36,022 - root - host_connect.py[line:31] - INFO >>> host更新成功： stage1
2017-11-16 14:12:36,023 - root - execution_case.py[line:14] - INFO >>> 开始执行用例
2017-11-16 14:12:36,040 - root - execution_case.py[line:27] - ERROR >>> 错误用例：行数-test_row_1  数据：OPEN
Traceback (most recent call last):
  File "D:\yimi_work\yimi_auto_test\utils\execution_case.py", line 25, in exe_cases
    a = 1/0
ZeroDivisionError: division by zero
2017-11-16 14:12:36,076 - root - execution_case.py[line:27] - ERROR >>> 错误用例：行数-test_row_2  数据：TYPE
Traceback (most recent call last):
  File "D:\yimi_work\yimi_auto_test\utils\execution_case.py", line 25, in exe_cases
    a = 1/0
ZeroDivisionError: division by zero
2017-11-16 14:12:36,076 - root - execution_case.py[line:27] - ERROR >>> 错误用例：行数-test_row_3  数据：CLICK
Traceback (most recent call last):
  File "D:\yimi_work\yimi_auto_test\utils\execution_case.py", line 25, in exe_cases
    a = 1/0
ZeroDivisionError: division by zero
2017-11-16 14:12:36,077 - root - execution_case.py[line:27] - ERROR >>> 错误用例：行数-test_row_4  数据：SLEEP
Traceback (most recent call last):
  File "D:\yimi_work\yimi_auto_test\utils\execution_case.py", line 25, in exe_cases
    a = 1/0
ZeroDivisionError: division by zero
2017-11-16 14:12:36,078 - root - execution_case.py[line:27] - ERROR >>> 错误用例：行数-test_row_5  数据：QUIT
Traceback (most recent call last):
  File "D:\yimi_work\yimi_auto_test\utils\execution_case.py", line 25, in exe_cases
    a = 1/0
ZeroDivisionError: division by zero
2017-11-16 14:12:36,078 - root - execution_case.py[line:30] - INFO >>> 执行用例成功
2017-11-16 14:13:12,648 - root - host_connect.py[line:27] - INFO >>> host开始更新： stage1
2017-11-16 14:13:12,651 - root - host_connect.py[line:31] - INFO >>> host更新成功： stage1
2017-11-16 14:13:12,651 - root - execution_case.py[line:14] - INFO >>> 开始执行用例
2017-11-16 14:13:12,669 - root - execution_case.py[line:27] - ERROR >>> 错误用例：行数 - 1  数据：OPEN
Traceback (most recent call last):
  File "D:\yimi_work\yimi_auto_test\utils\execution_case.py", line 25, in exe_cases
    a = 1/0
ZeroDivisionError: division by zero
2017-11-16 14:13:12,670 - root - execution_case.py[line:27] - ERROR >>> 错误用例：行数 - 2  数据：TYPE
Traceback (most recent call last):
  File "D:\yimi_work\yimi_auto_test\utils\execution_case.py", line 25, in exe_cases
    a = 1/0
ZeroDivisionError: division by zero
2017-11-16 14:13:12,670 - root - execution_case.py[line:27] - ERROR >>> 错误用例：行数 - 3  数据：CLICK
Traceback (most recent call last):
  File "D:\yimi_work\yimi_auto_test\utils\execution_case.py", line 25, in exe_cases
    a = 1/0
ZeroDivisionError: division by zero
2017-11-16 14:13:12,671 - root - execution_case.py[line:27] - ERROR >>> 错误用例：行数 - 4  数据：SLEEP
Traceback (most recent call last):
  File "D:\yimi_work\yimi_auto_test\utils\execution_case.py", line 25, in exe_cases
    a = 1/0
ZeroDivisionError: division by zero
2017-11-16 14:13:12,671 - root - execution_case.py[line:27] - ERROR >>> 错误用例：行数 - 5  数据：QUIT
Traceback (most recent call last):
  File "D:\yimi_work\yimi_auto_test\utils\execution_case.py", line 25, in exe_cases
    a = 1/0
ZeroDivisionError: division by zero
2017-11-16 14:13:12,671 - root - execution_case.py[line:30] - INFO >>> 执行用例成功
2017-11-16 14:13:49,873 - root - host_connect.py[line:27] - INFO >>> host开始更新： stage1
2017-11-16 14:13:49,875 - root - host_connect.py[line:31] - INFO >>> host更新成功： stage1
2017-11-16 14:13:49,875 - root - execution_case.py[line:14] - INFO >>> 开始执行用例
2017-11-16 14:13:49,893 - root - execution_case.py[line:27] - ERROR >>> 错误用例：行数 - 1  数据：OPEN
Traceback (most recent call last):
  File "D:\yimi_work\yimi_auto_test\utils\execution_case.py", line 25, in exe_cases
    a = 1/0
ZeroDivisionError: division by zero
2017-11-16 14:14:48,473 - root - host_connect.py[line:27] - INFO >>> host开始更新： stage1
2017-11-16 14:14:48,476 - root - host_connect.py[line:31] - INFO >>> host更新成功： stage1
2017-11-16 14:14:48,477 - root - execution_case.py[line:14] - INFO >>> 开始执行用例
2017-11-16 14:14:48,494 - root - execution_case.py[line:28] - ERROR >>> 错误用例：行数 - 1  数据：OPENhttps://www.baidu.com/
Traceback (most recent call last):
  File "D:\yimi_work\yimi_auto_test\utils\execution_case.py", line 25, in exe_cases
    a = 1/0
ZeroDivisionError: division by zero
2017-11-16 14:15:18,153 - root - host_connect.py[line:27] - INFO >>> host开始更新： stage1
2017-11-16 14:15:18,156 - root - host_connect.py[line:31] - INFO >>> host更新成功： stage1
2017-11-16 14:15:18,157 - root - execution_case.py[line:14] - INFO >>> 开始执行用例
2017-11-16 14:15:18,173 - root - execution_case.py[line:28] - ERROR >>> 错误用例：行数 - 1  数据：OPEN    https://www.baidu.com/    
Traceback (most recent call last):
  File "D:\yimi_work\yimi_auto_test\utils\execution_case.py", line 25, in exe_cases
    a = 1/0
ZeroDivisionError: division by zero
2017-11-16 14:15:42,519 - root - host_connect.py[line:27] - INFO >>> host开始更新： stage1
2017-11-16 14:15:42,521 - root - host_connect.py[line:31] - INFO >>> host更新成功： stage1
2017-11-16 14:15:42,521 - root - execution_case.py[line:14] - INFO >>> 开始执行用例
2017-11-16 14:15:42,538 - root - execution_case.py[line:28] - ERROR >>> 错误用例：行数 - 1  数据：OPEN        https://www.baidu.com/    
Traceback (most recent call last):
  File "D:\yimi_work\yimi_auto_test\utils\execution_case.py", line 25, in exe_cases
    a = 1/0
ZeroDivisionError: division by zero
2017-11-16 14:16:34,485 - root - host_connect.py[line:27] - INFO >>> host开始更新： stage1
2017-11-16 14:16:34,488 - root - host_connect.py[line:31] - INFO >>> host更新成功： stage1
2017-11-16 14:16:34,489 - root - execution_case.py[line:14] - INFO >>> 开始执行用例
2017-11-16 14:16:34,489 - root - ary.py[line:22] - INFO >>> 开始打开chrome浏览器
2017-11-16 14:16:38,596 - root - ary.py[line:30] - INFO >>> 打开浏览器成功
2017-11-16 14:16:50,014 - root - execution_case.py[line:29] - INFO >>> 执行用例成功
2017-11-16 16:47:55,849 - root - host_connect.py[line:27] - INFO >>> host开始更新： stage1
2017-11-16 16:47:55,962 - root - host_connect.py[line:31] - INFO >>> host更新成功： stage1
2017-11-16 16:47:55,962 - root - execution_case.py[line:14] - INFO >>> 开始执行用例
2017-11-16 16:47:55,963 - root - ary.py[line:22] - INFO >>> 开始打开chrome浏览器
2017-11-16 16:47:59,895 - root - ary.py[line:30] - INFO >>> 打开浏览器成功
2017-11-16 16:48:11,299 - root - execution_case.py[line:35] - INFO >>> 执行用例成功
2017-11-16 17:09:16,153 - root - host_connect.py[line:27] - INFO >>> host开始更新： stage1
2017-11-16 17:09:16,156 - root - host_connect.py[line:31] - INFO >>> host更新成功： stage1
2017-11-16 17:09:16,156 - root - execution_case.py[line:14] - INFO >>> 开始执行用例
2017-11-16 17:09:16,157 - root - ary.py[line:22] - INFO >>> 开始打开chrome浏览器
2017-11-16 17:09:19,872 - root - ary.py[line:30] - INFO >>> 打开浏览器成功
2017-11-16 17:09:51,973 - root - execution_case.py[line:35] - INFO >>> 执行用例成功
2017-11-16 17:13:38,254 - root - host_connect.py[line:27] - INFO >>> host开始更新： stage1
2017-11-16 17:13:38,256 - root - host_connect.py[line:31] - INFO >>> host更新成功： stage1
2017-11-16 17:13:38,256 - root - execution_case.py[line:14] - INFO >>> 开始执行用例
2017-11-16 17:13:38,257 - root - ary.py[line:22] - INFO >>> 开始打开chrome浏览器
2017-11-16 17:13:41,974 - root - ary.py[line:30] - INFO >>> 打开浏览器成功
2017-11-16 17:13:54,206 - root - execution_case.py[line:35] - INFO >>> 执行用例成功
2017-11-16 17:14:33,414 - root - host_connect.py[line:27] - INFO >>> host开始更新： stage1
2017-11-16 17:14:33,416 - root - host_connect.py[line:31] - INFO >>> host更新成功： stage1
2017-11-16 17:14:33,417 - root - execution_case.py[line:14] - INFO >>> 开始执行用例
2017-11-16 17:14:33,417 - root - ary.py[line:22] - INFO >>> 开始打开chrome浏览器
2017-11-16 17:14:37,118 - root - ary.py[line:30] - INFO >>> 打开浏览器成功
2017-11-16 17:14:54,688 - root - execution_case.py[line:35] - INFO >>> 执行用例成功
2017-11-16 17:15:04,152 - root - host_connect.py[line:27] - INFO >>> host开始更新： stage1
2017-11-16 17:15:04,156 - root - host_connect.py[line:31] - INFO >>> host更新成功： stage1
2017-11-16 17:15:04,156 - root - execution_case.py[line:14] - INFO >>> 开始执行用例
2017-11-16 17:15:04,156 - root - ary.py[line:22] - INFO >>> 开始打开chrome浏览器
2017-11-16 17:15:07,859 - root - ary.py[line:30] - INFO >>> 打开浏览器成功
2017-11-16 17:15:19,609 - root - execution_case.py[line:35] - INFO >>> 执行用例成功
2017-11-16 17:15:47,947 - root - host_connect.py[line:27] - INFO >>> host开始更新： stage1
2017-11-16 17:15:47,950 - root - host_connect.py[line:31] - INFO >>> host更新成功： stage1
2017-11-16 17:15:47,951 - root - execution_case.py[line:14] - INFO >>> 开始执行用例
2017-11-16 17:15:47,951 - root - ary.py[line:22] - INFO >>> 开始打开chrome浏览器
2017-11-16 17:15:51,613 - root - ary.py[line:30] - INFO >>> 打开浏览器成功
2017-11-16 17:16:04,090 - root - execution_case.py[line:35] - INFO >>> 执行用例成功
2017-11-16 18:00:17,624 - root - host_connect.py[line:27] - INFO >>> host开始更新： stage1
2017-11-16 18:00:17,627 - root - host_connect.py[line:31] - INFO >>> host更新成功： stage1
2017-11-16 18:00:17,627 - root - execution_case.py[line:14] - INFO >>> 开始执行用例
2017-11-16 18:00:17,628 - root - ary.py[line:22] - INFO >>> 开始打开chrome浏览器
2017-11-16 18:00:21,347 - root - ary.py[line:30] - INFO >>> 打开浏览器成功
2017-11-16 18:00:37,276 - root - execution_case.py[line:35] - INFO >>> 执行用例成功
2017-11-16 18:00:46,227 - root - host_connect.py[line:27] - INFO >>> host开始更新： stage1
2017-11-16 18:00:46,229 - root - host_connect.py[line:31] - INFO >>> host更新成功： stage1
2017-11-16 18:00:46,230 - root - execution_case.py[line:14] - INFO >>> 开始执行用例
2017-11-16 18:00:46,230 - root - ary.py[line:22] - INFO >>> 开始打开chrome浏览器
2017-11-16 18:00:49,885 - root - ary.py[line:30] - INFO >>> 打开浏览器成功
2017-11-16 18:01:01,819 - root - execution_case.py[line:35] - INFO >>> 执行用例成功
2017-11-16 18:03:52,990 - root - host_connect.py[line:27] - INFO >>> host开始更新： stage1
2017-11-16 18:03:52,992 - root - host_connect.py[line:31] - INFO >>> host更新成功： stage1
2017-11-16 18:03:52,993 - root - execution_case.py[line:14] - INFO >>> 开始执行用例
2017-11-16 18:03:52,993 - root - ary.py[line:22] - INFO >>> 开始打开chrome浏览器
2017-11-16 18:03:56,658 - root - ary.py[line:30] - INFO >>> 打开浏览器成功
2017-11-16 18:04:24,086 - root - execution_case.py[line:33] - ERROR >>> 执行用例失败，错误用例：行数 - 8  数据：CLICK    /html/body/div[1]/div[2]/div/ul/li[2]/ul/li[1]/a        
Traceback (most recent call last):
  File "D:\yimi_work\yimi_auto_test\utils\execution_case.py", line 28, in exe_cases
    exe_case(driver=driver, operation=operation, path=path, value=value, dp=dp)
  File "D:\yimi_work\yimi_auto_test\utils\execution_case.py", line 56, in exe_case
    driver.click(path)
  File "D:\yimi_work\yimi_auto_test\utils\ary.py", line 99, in click
    self.element_wait(xpath)
  File "D:\yimi_work\yimi_auto_test\utils\ary.py", line 35, in element_wait
    WebDriverWait(self.driver, 5).until(EC.presence_of_all_elements_located((By.XPATH, xpath)))
  File "C:\Users\suMs\AppData\Local\Programs\Python\Python36-32\lib\site-packages\selenium\webdriver\support\wait.py", line 71, in until
    value = method(self._driver)
  File "C:\Users\suMs\AppData\Local\Programs\Python\Python36-32\lib\site-packages\selenium\webdriver\support\expected_conditions.py", line 111, in __call__
    return _find_elements(driver, self.locator)
  File "C:\Users\suMs\AppData\Local\Programs\Python\Python36-32\lib\site-packages\selenium\webdriver\support\expected_conditions.py", line 339, in _find_elements
    raise e
  File "C:\Users\suMs\AppData\Local\Programs\Python\Python36-32\lib\site-packages\selenium\webdriver\support\expected_conditions.py", line 337, in _find_elements
    return driver.find_elements(*by)
  File "C:\Users\suMs\AppData\Local\Programs\Python\Python36-32\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 782, in find_elements
    'value': value})['value']
  File "C:\Users\suMs\AppData\Local\Programs\Python\Python36-32\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 238, in execute
    self.error_handler.check_response(response)
  File "C:\Users\suMs\AppData\Local\Programs\Python\Python36-32\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 193, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: chrome not reachable
  (Session info: chrome=55.0.2883.87)
  (Driver info: chromedriver=2.25.426923 (0390b88869384d6eb0d5d09729679f934aab9eed),platform=Windows NT 10.0.14393 x86_64)

2017-11-16 18:05:12,764 - root - host_connect.py[line:27] - INFO >>> host开始更新： stage1
2017-11-16 18:05:12,766 - root - host_connect.py[line:31] - INFO >>> host更新成功： stage1
2017-11-16 18:05:12,767 - root - execution_case.py[line:14] - INFO >>> 开始执行用例
2017-11-16 18:05:12,767 - root - ary.py[line:22] - INFO >>> 开始打开chrome浏览器
2017-11-16 18:05:16,458 - root - ary.py[line:30] - INFO >>> 打开浏览器成功
2017-11-16 18:05:37,826 - root - execution_case.py[line:35] - INFO >>> 执行用例成功
2017-11-16 18:06:11,302 - root - host_connect.py[line:27] - INFO >>> host开始更新： stage1
2017-11-16 18:06:11,304 - root - host_connect.py[line:31] - INFO >>> host更新成功： stage1
2017-11-16 18:06:11,305 - root - execution_case.py[line:14] - INFO >>> 开始执行用例
2017-11-16 18:06:11,305 - root - ary.py[line:22] - INFO >>> 开始打开chrome浏览器
2017-11-16 18:06:14,968 - root - ary.py[line:30] - INFO >>> 打开浏览器成功
2017-11-16 18:07:01,078 - root - host_connect.py[line:27] - INFO >>> host开始更新： stage1
2017-11-16 18:07:01,081 - root - host_connect.py[line:31] - INFO >>> host更新成功： stage1
2017-11-16 18:07:01,081 - root - execution_case.py[line:14] - INFO >>> 开始执行用例
2017-11-16 18:07:01,081 - root - ary.py[line:22] - INFO >>> 开始打开chrome浏览器
2017-11-16 18:07:04,763 - root - ary.py[line:30] - INFO >>> 打开浏览器成功
2017-11-16 18:07:26,976 - root - execution_case.py[line:35] - INFO >>> 执行用例成功
2017-11-16 18:11:16,006 - root - host_connect.py[line:27] - INFO >>> host开始更新： stage1
2017-11-16 18:11:16,010 - root - host_connect.py[line:31] - INFO >>> host更新成功： stage1
2017-11-16 18:11:16,010 - root - execution_case.py[line:14] - INFO >>> 开始执行用例
2017-11-16 18:11:16,011 - root - ary.py[line:22] - INFO >>> 开始打开chrome浏览器
2017-11-16 18:11:19,692 - root - ary.py[line:30] - INFO >>> 打开浏览器成功
2017-11-16 18:11:28,799 - root - host_connect.py[line:27] - INFO >>> host开始更新： stage1
2017-11-16 18:11:28,803 - root - host_connect.py[line:31] - INFO >>> host更新成功： stage1
2017-11-16 18:11:28,803 - root - execution_case.py[line:14] - INFO >>> 开始执行用例
2017-11-16 18:11:28,803 - root - ary.py[line:22] - INFO >>> 开始打开chrome浏览器
2017-11-16 18:11:32,465 - root - ary.py[line:30] - INFO >>> 打开浏览器成功
2017-11-16 18:15:37,303 - root - host_connect.py[line:27] - INFO >>> host开始更新： stage1
2017-11-16 18:15:37,305 - root - host_connect.py[line:31] - INFO >>> host更新成功： stage1
2017-11-16 18:15:37,306 - root - execution_case.py[line:14] - INFO >>> 开始执行用例
2017-11-16 18:15:37,306 - root - ary.py[line:22] - INFO >>> 开始打开chrome浏览器
2017-11-16 18:15:41,011 - root - ary.py[line:30] - INFO >>> 打开浏览器成功
2017-11-16 18:15:54,700 - root - host_connect.py[line:27] - INFO >>> host开始更新： stage1
2017-11-16 18:15:54,703 - root - host_connect.py[line:31] - INFO >>> host更新成功： stage1
2017-11-16 18:15:54,703 - root - execution_case.py[line:14] - INFO >>> 开始执行用例
2017-11-16 18:15:54,704 - root - ary.py[line:22] - INFO >>> 开始打开chrome浏览器
2017-11-16 18:15:58,390 - root - ary.py[line:30] - INFO >>> 打开浏览器成功
2017-11-16 18:16:11,805 - root - execution_case.py[line:35] - INFO >>> 执行用例成功
2017-11-17 10:37:50,942 - root - host_connect.py[line:27] - INFO >>> host开始更新： stage1
2017-11-17 10:37:50,990 - root - host_connect.py[line:31] - INFO >>> host更新成功： stage1
2017-11-17 10:37:50,990 - root - execution_case.py[line:14] - INFO >>> 开始执行用例
2017-11-17 10:37:50,990 - root - ary.py[line:24] - INFO >>> 开始打开chrome浏览器
2017-11-17 10:37:54,696 - root - ary.py[line:32] - INFO >>> 打开浏览器成功
2017-11-17 10:37:54,714 - root - execution_case.py[line:122] - WARNING >>> 错误的操作
2017-11-17 10:37:57,892 - root - execution_case.py[line:33] - ERROR >>> 执行用例失败，错误用例：行数 - 1  数据：        https://www.baidu.com/    
Traceback (most recent call last):
  File "D:\yimi_work\yimi_auto_test\utils\execution_case.py", line 28, in exe_cases
    exe_case(driver=driver, operation=operation, path=path, value=value, dp=dp)
  File "D:\yimi_work\yimi_auto_test\utils\execution_case.py", line 123, in exe_case
    raise BaseException('错误的操作')
BaseException: 错误的操作
2017-11-17 10:39:32,177 - root - host_connect.py[line:27] - INFO >>> host开始更新： stage1
2017-11-17 10:39:32,186 - root - host_connect.py[line:31] - INFO >>> host更新成功： stage1
2017-11-17 10:39:32,186 - root - execution_case.py[line:14] - INFO >>> 开始执行用例
2017-11-17 10:39:32,187 - root - ary.py[line:24] - INFO >>> 开始打开chrome浏览器
2017-11-17 10:39:35,868 - root - ary.py[line:32] - INFO >>> 打开浏览器成功
2017-11-17 10:39:35,883 - root - execution_case.py[line:125] - WARNING >>> 错误的操作
2017-11-17 10:39:39,004 - root - execution_case.py[line:36] - ERROR >>> 执行用例失败，错误用例：行数 - 1  数据：operation:    path:    value:https://www.baidu.com/    dp:
Traceback (most recent call last):
  File "D:\yimi_work\yimi_auto_test\utils\execution_case.py", line 28, in exe_cases
    exe_case(driver=driver, operation=operation, path=path, value=value, dp=dp)
  File "D:\yimi_work\yimi_auto_test\utils\execution_case.py", line 126, in exe_case
    raise BaseException('错误的操作')
BaseException: 错误的操作
2017-11-17 10:56:13,125 - root - host_connect.py[line:27] - INFO >>> host开始更新： stage1
2017-11-17 10:56:13,128 - root - host_connect.py[line:31] - INFO >>> host更新成功： stage1
2017-11-17 10:56:13,129 - root - execution_case.py[line:14] - INFO >>> 开始执行用例
2017-11-17 10:56:13,129 - root - ary.py[line:24] - INFO >>> 开始打开chrome浏览器
2017-11-17 10:56:16,800 - root - ary.py[line:32] - INFO >>> 打开浏览器成功
2017-11-17 10:56:42,791 - root - execution_case.py[line:38] - INFO >>> 执行用例成功
2017-11-17 10:57:54,318 - root - host_connect.py[line:27] - INFO >>> host开始更新： stage1
2017-11-17 10:57:54,320 - root - host_connect.py[line:31] - INFO >>> host更新成功： stage1
2017-11-17 10:57:54,321 - root - execution_case.py[line:14] - INFO >>> 开始执行用例
2017-11-17 10:57:54,321 - root - ary.py[line:24] - INFO >>> 开始打开chrome浏览器
2017-11-17 10:57:58,014 - root - ary.py[line:32] - INFO >>> 打开浏览器成功
2017-11-17 11:19:31,381 - root - host_connect.py[line:28] - INFO >>> host开始更新： stage1
2017-11-17 11:19:31,387 - root - host_connect.py[line:42] - INFO >>> host开始判断环境
2017-11-17 11:19:31,402 - root - host_connect.py[line:33] - INFO >>> host更新成功： stage1
2017-11-17 11:19:52,284 - root - host_connect.py[line:28] - INFO >>> host开始更新： prod
2017-11-17 11:19:52,358 - root - host_connect.py[line:33] - INFO >>> host更新成功： prod
2017-11-17 11:27:15,053 - root - host_connect.py[line:28] - INFO >>> host开始更新： prod
2017-11-17 11:27:15,096 - root - host_connect.py[line:34] - INFO >>> host更新成功： prod
2017-11-17 11:27:31,755 - root - host_connect.py[line:28] - INFO >>> host开始更新： prod
2017-11-17 11:27:31,789 - root - host_connect.py[line:35] - INFO >>> host更新成功： prod
2017-11-17 11:31:33,385 - root - host_connect.py[line:28] - INFO >>> host开始更新： prod
2017-11-17 11:31:33,592 - root - host_connect.py[line:37] - ERROR >>> host更新失败： prod
2017-11-17 13:22:18,456 - root - host_connect.py[line:28] - INFO >>> host开始更新： stage1
2017-11-17 13:22:18,476 - root - host_connect.py[line:35] - INFO >>> host更新成功： stage1
2017-11-17 13:22:18,476 - root - execution_case.py[line:14] - INFO >>> 开始执行用例
2017-11-17 13:22:18,476 - root - ary.py[line:24] - INFO >>> 开始打开chrome浏览器
2017-11-17 13:22:22,200 - root - ary.py[line:32] - INFO >>> 打开浏览器成功
2017-11-17 13:22:22,223 - root - excel_wr.py[line:38] - ERROR >>> 数据错误:当前行：1  当前行数据：{'id': 0.0, 'operation': 'open', 'path': '', 'value': 'http://mis.1mifudao.com/', 'dp': '', 'memo': '打开mis'}
Traceback (most recent call last):
  File "D:\yimi_work\yimi_auto_test\utils\excel_wr.py", line 36, in rexcel
    check_data(dictdata)
  File "D:\yimi_work\yimi_auto_test\utils\excel_wr.py", line 61, in check_data
    raise BaseException('用例错误，存在错误的操作')
BaseException: 用例错误，存在错误的操作
2017-11-17 13:22:53,292 - root - host_connect.py[line:28] - INFO >>> host开始更新： stage1
2017-11-17 13:22:53,311 - root - host_connect.py[line:35] - INFO >>> host更新成功： stage1
2017-11-17 13:22:53,326 - root - excel_wr.py[line:38] - ERROR >>> 数据错误:当前行：1  当前行数据：{'id': 0.0, 'operation': 'open', 'path': '', 'value': 'http://mis.1mifudao.com/', 'dp': '', 'memo': '打开mis'}
Traceback (most recent call last):
  File "D:\yimi_work\yimi_auto_test\utils\excel_wr.py", line 36, in rexcel
    check_data(dictdata)
  File "D:\yimi_work\yimi_auto_test\utils\excel_wr.py", line 61, in check_data
    raise BaseException('用例错误，存在错误的操作')
BaseException: 用例错误，存在错误的操作
2017-11-17 13:23:17,857 - root - host_connect.py[line:28] - INFO >>> host开始更新： stage1
2017-11-17 13:23:17,874 - root - host_connect.py[line:33] - INFO >>> host更新成功： stage1
2017-11-17 13:23:17,889 - root - excel_wr.py[line:38] - ERROR >>> 数据错误:当前行：1  当前行数据：{'id': 0.0, 'operation': 'open', 'path': '', 'value': 'http://mis.1mifudao.com/', 'dp': '', 'memo': '打开mis'}
Traceback (most recent call last):
  File "D:\yimi_work\yimi_auto_test\utils\excel_wr.py", line 36, in rexcel
    check_data(dictdata)
  File "D:\yimi_work\yimi_auto_test\utils\excel_wr.py", line 61, in check_data
    raise BaseException('用例错误，存在错误的操作')
BaseException: 用例错误，存在错误的操作
2017-11-17 13:25:29,467 - root - host_connect.py[line:28] - INFO >>> host开始更新： stage1
2017-11-17 13:25:29,483 - root - host_connect.py[line:33] - INFO >>> host更新成功： stage1
2017-11-17 13:25:29,499 - root - execution_case.py[line:16] - INFO >>> 开始执行用例
2017-11-17 13:25:29,499 - root - ary.py[line:24] - INFO >>> 开始打开chrome浏览器
2017-11-17 13:25:33,197 - root - ary.py[line:32] - INFO >>> 打开浏览器成功
2017-11-17 13:26:08,689 - root - host_connect.py[line:28] - INFO >>> host开始更新： stage1
2017-11-17 13:26:08,708 - root - host_connect.py[line:33] - INFO >>> host更新成功： stage1
2017-11-17 13:26:08,725 - root - excel_wr.py[line:53] - INFO >>> 用例列数错误：标准列数：6，当前列数：7
